### ISSUE TITLE
I can't seems to install it on hosting

### ISSUE THREAD

**Issue by madromas** [phpSoftware/esoTalk-v2#1]
I can't install it on hosting. php 7.4

But it works on localhost xampp.

But, when you start a topic, it only shows Title, but not the topic it self. Also Video links don't work.

Please update to MariaDB and php7.4

**Comment by phpSoftware** [comment]
Nice to hear from you, 

what PHP and MySQL/MariaDB Versio do you use on xampp localhost?

> Please update to MariaDB and php7.4

Submit a Patch, use a pull request and you will get all the honor ;-)

**Comment by madromas** [comment]
PHP/7.4.23 
mysql  Ver 15.1 Distrib 10.4.21-MariaDB, for Win64 (AMD64), 

It works just fine in here, besides, the topic content and videos not showing...

On my hosting I can't even install it, keep saying Fatal error.

I can't submit patch, As I have no idea how to fix this.

**Comment by phpSoftware** [comment]
1. it works with all functions correct on my system
2. "topic content and videos not showing" post a screenshot from the page in the browser and also from the HTML Source
3. What PHP and SLQ Versions do you use on you web hosting, please send link and FTP data by mail
4. Please read this ;-) https://boyter.org/posts/the-three-f-s-of-open-source/

**Comment by madromas** [comment]
1. Here is a print screen from Xampp. As you can see I quoted the text in topic, but it does not show in topic itself.

![notext](https://user-images.githubusercontent.com/64708726/147617235-55daa3b1-8f7c-42f5-bc85-bad024a50a96.jpg)

As you can see in Source code, it's not showing.
![text](https://user-images.githubusercontent.com/64708726/147617355-b5df80dd-7f48-4389-92f7-089a9f491cf5.jpg)

Maybe because I use https and not http? 

I will change script to https and see if anything changes. Nope.
This is what I get when trying to install on Hosting:

![error](https://user-images.githubusercontent.com/64708726/147617972-103e74e2-3d58-436c-b01b-9fc5c9a89de7.jpg)

Hosting stats
     LiteSpeed
    Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: 3591daad22de08524295e1bd073aceeff11e6579 $
    PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
    PHP version: 7.2.34

    Server: DA PMA Signon (Localhost via UNIX socket)
    Server type: MariaDB
    Server connection: SSL is not being used Documentation
    Server version: 10.3.32-MariaDB-cll-lve - MariaDB Server
    Protocol version: 10
   
P.S. Not sure what you imply by Number 4. 

PSS. Without me being able to install it on hosting and see posts, I cannot get familiar with this forum and write plugins or add-ons and what not.

**Comment by phpSoftware** [comment]
You could open the file `config.defaults.php` and change:

`$config["esoTalk.debug"] = true;`

so you will see the problems and fix it ;-)

**Comment by phpSoftware** [comment]
Please download and try the new Version (i make some changes) and for me, it now works with PHP 7.4

**Comment by madromas** [comment]
Thank you so much for this. I did not see the debug option. I was able to install it by replacing this line in : **/core/lib/ETDatabase.class.php line 126**

`$this->query("SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));")->result();`

With this:

`$this->query("SET sql_mode=(SELECT REPLACE(@@sql_mode, 'ONLY_FULL_GROUP_BY', ''));")->result();`

**Comment by madromas** [comment]
Update. With the debug mode set to true, there is some errors. No big deal. Because they disappear when I set it to false.

![lol](https://user-images.githubusercontent.com/64708726/147670047-b6dcdc71-dca0-48e3-a41a-ac60a75080c3.jpg)

But, I will keep it in true, and see if I can fix some of them.

Update N2. Posts are now showing in topic :)  Now that I have it installed, I can look deeper in a code, and see if I can contribute to this project.

**Comment by phpSoftware** [comment]
> Thank you so much for this. I did not see the debug option. I was able to install it by replacing this line in : **/core/lib/ETDatabase.class.php line 126**
> 
> `$this->query("SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));")->result();`
> 
> With this:
> 
> `$this->query("SET sql_mode=(SELECT REPLACE(@@sql_mode, 'ONLY_FULL_GROUP_BY', ''));")->result();`

updated the repo

**Comment by phpSoftware** [comment]
> Update. With the debug mode set to true, there are some errors. No big deal. Because they disappear when I set it to false.
> But, I will keep it true, and see if I can fix some of them.

The Notice and Warnings can be ignored, but if you see anything else it would be nice if you inform me so I can fix it here also

> Update N2. Posts are now showing in topic :) Now that I have it installed, I can look deeper into the code, and see if I can contribute to this project.

That would be very kind, I would be happy if I get a contributor for this project

**Comment by madromas** [comment]
[Reputation-master.zip](https://github.com/phpSoftware/esoTalk-v2/files/7789774/Reputation-master.zip)

![rep](https://user-images.githubusercontent.com/64708726/147683369-3ca62e1a-b9ac-4329-b072-550dde20bf44.jpg)


Found Reputation addon, that can be added to core :)

**Comment by madromas** [comment]
Akismet - Anti-spammer plugin
[Akismet.zip](https://github.com/phpSoftware/esoTalk-v2/files/7789861/Akismet.zip)

**Comment by madromas** [comment]
Adds featured post. :)

[Featured.zip](https://github.com/phpSoftware/esoTalk-v2/files/7789903/Featured.zip)

**Comment by madromas** [comment]
Gravatar for Eso
[Gravatar.zip](https://github.com/phpSoftware/esoTalk-v2/files/7789979/Gravatar.zip)

Every thing is tested and working. In this one, you need to force https in config $config["esoTalk.https"] = true; // Whether or not to force HTTPS. Otherwise avatars will show as blanks.

**Comment by madromas** [comment]
.unreadIndicator {
    font-size: 12px;
    font-weight: 700;
    color: #fff;
    padding: 0 5px;
    border-radius: 3px;
    margin-right: 5px;
}

Better set color to #e44, so it's not white on white, and stand up better.

**Comment by madromas** [comment]
Shadow Ban Hide one or all of a member's posts without them being aware.
[ShadowBan.zip](https://github.com/phpSoftware/esoTalk-v2/files/7790079/ShadowBan.zip)

Tiny problem IF your forum is not in a root, you will have to add subfolder to plugin.php. Before "members", like so "SUB/members". If this gets added to core, than I will look in to how to edit it without users adding nothing.

**Comment by madromas** [comment]
![github](https://user-images.githubusercontent.com/64708726/147691723-d9138768-fb6c-40d7-abf6-b977b276da23.jpg)
GitHub Links Parses posts for issue numbers (#123) and commit hashes (abc1234) and links them to GitHub.
[GitHubLinks.zip](https://github.com/phpSoftware/esoTalk-v2/files/7790107/GitHubLinks.zip)

Tested working.

Channel notifications:
[ChannelNotifications.zip](https://github.com/phpSoftware/esoTalk-v2/files/7790142/ChannelNotifications.zip)


One thing this forum is missing, is Synopsis. To show content of first topic on main page under the Title. Like a summary.  :(((

**Comment by madromas** [comment]
In every skin on mobile.css better set it to inline-block or flex or whatever.  or lover 80% to 60 or so. Otherwise logo drops under. 

#hdr #forumTitle {
    `display: inline-flex;`
    width: 80%;

**Comment by madromas** [comment]
I came across another issue, sticky and new posts on top don't work, new post add to bottom and sticky don't stick to top.

**Comment by madromas** [comment]
Willing to work? Need few things done. For money of course.

**Comment by madromas** [comment]
I fixed a bug, about new posts or new reply's not showing on top

**Comment by phpSoftware** [comment]
> In every skin on mobile.css better set it to inline-block or flex or whatever. or lover 80% to 60 or so. Otherwise logo drops under.
> 
> #hdr #forumTitle { `display: inline-flex;` width: 80%;

Will get into this in the next few days

**Comment by phpSoftware** [comment]
> Willing to work? Need few things done. For money of course.

For sure possible, what should be done write me 5557720max at Gmail dot com and you will get a quote (PayPal should be possible)

**Comment by madromas** [comment]
Forgot: in file **core/views/conversations/list.php**

This line needs to be removed, or worked on. It is preventing the new topics or reply's to be on top.

```
// vanGato - TODO: SORT STARTPAGE BY channelId - ADD if isset()
array_multisort(array_map(function($element) {if (isset($element[2]['channelId'])) {return $element[2]['channelId'];}else{return '';}}, $data["results"]), SORT_ASC, $data["results"]);
```

**Comment by madromas** [comment]
The job is kinda simple. You know how excerpt shows up on;y on Sticky topics(the preview below topic title)? Well, I want it to show up for every topic, not just sticky.

**Comment by phpSoftware** [comment]
> unreadIndicator

In what Skin and File do you edit this?
Or do you add it to custom.css ?

**Comment by phpSoftware** [comment]
> Forgot: in file **core/views/conversations/list.php**
> 
> This line needs to be removed, or worked on. It is preventing the new topics or reply's to be on top.
> 
> ```
> // vanGato - TODO: SORT STARTPAGE BY channelId - ADD if isset()
> array_multisort(array_map(function($element) {if (isset($element[2]['channelId'])) {return $element[2]['channelId'];}else{return '';}}, $data["results"]), SORT_ASC, $data["results"]);
> ```

Yes i know, i implement this because i want the page sorted by id ;-)

**Comment by madromas** [comment]
> > unreadIndicator
> 
> In what Skin and File do you edit this? Or do you add it to custom.css ?

What do you mean?

> Yes i know, i implement this because i want the page sorted by id ;-)

May I ask what is a purpose of that?

**Comment by phpSoftware** [comment]
> What do you mean?

```
.unreadIndicator {
  font-size: 12px;
  font-weight: 700;
  color: #fff;
  padding: 0 5px;
  border-radius: 3px;
  margin-right: 5px;
}
```

In what Skin and File do you edit this? Or do you add it to custom.css ?

**Comment by madromas** [comment]
It's originally in base.css. But if you want to apply it only to specific skin, than copy that style to skin/style.css
