### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by pwFoo** [phpSoftware/esoTalk-v2#10]
Hi,
I liked esotalk and found that repo... is it still maintained? Is PHP 8 support planned?

**Comment by gaffling** [comment]
Last changes are made 2 Years ago, don't know if it's running under PHP 8, but maybe give it a try and send feedback ;-)

**Comment by madromas** [comment]
It is not supported by PHP 8. Wish I knew how to upgrade it.

**Comment by madromas** [comment]
I have fixed the php 8 support!

https://github.com/madromas/esoTalk-v3

Test: https://hub.madway.net

**Comment by phpSoftware** [comment]
-
