### ISSUE TITLE
Unable to communicate with the server. Wait a few seconds and try again, or refresh the page.

### ISSUE THREAD

**Issue by kosmodrum12** [phpSoftware/esoTalk-v2#4]
When I post a new topic, it displays this as an error at the bottom left **Unable to communicate with the server. Wait a few seconds and try again, or refresh the page.,** but when refreshing the forum, the topic is posted, but when you click on it;

Something Went Wrong
The Forum has encountered a fatal error.

**Comment by kosmodrum12** [comment]
PS: Errors from debug;

`Warning: Declaration of ETSession::get($key, $default = NULL) should be compatible with ETModel::get($wheres = Array) in C:\xampp\htdocs\eso\core\lib\ETSession.class.php on line 461

Warning: Declaration of ETMemberModel::create(&$values) should be compatible with ETModel::create($values) in C:\xampp\htdocs\eso\core\models\ETMemberModel.class.php on line 47

Notice: Only variables should be passed by reference in C:\xampp\htdocs\eso\core\models\ETMemberModel.class.php on line 169

Notice: Accessing static property ETPlugin_Featured::$icon_featured as non static in C:\xampp\htdocs\eso\addons\plugins\Featured\plugin.php on line 19

Notice: Accessing static property ETPlugin_Featured::$icon_featured as non static in C:\xampp\htdocs\eso\addons\plugins\Featured\plugin.php on line 25

Warning: Declaration of ETActivityModel::create($type, $member, $fromMember = NULL, $data = NULL, $emailData = NULL) should be compatible with ETModel::create($values) in C:\xampp\htdocs\eso\core\models\ETActivityModel.class.php on line 101

Warning: Declaration of ETPlugin_reCAPTCHA::setup() should be compatible with ETPlugin::setup($oldVersion = '') in C:\xampp\htdocs\eso\addons\plugins\reCAPTCHA\plugin.php on line 22

Warning: Declaration of ETPlugin_Signature::setup() should be compatible with ETPlugin::setup($oldVersion = '') in C:\xampp\htdocs\eso\addons\plugins\Signature\plugin.php on line 110`

**Comment by phpSoftware** [comment]
Looks like there are Problems with a Plugin, please switch off all plugins and try it again.
If it works, switch on the first plugin and give it a try, if it still works, do this step by step so you will find the addon that causes the problem.

Have you made any changes?


PS: Please also read this for how-to-use open-source on GitHub ;-)
https://boyter.org/posts/the-three-f-s-of-open-source/

**Comment by kosmodrum12** [comment]
I disabled all plugins and that's it:

`Warning: Declaration of ETSession::get($key, $default = NULL) should be compatible with ETModel::get($wheres = Array) in C:\xampp\htdocs\eso\core\lib\ETSession.class.php on line 461

Warning: Declaration of ETMemberModel::create(&$values) should be compatible with ETModel::create($values) in C:\xampp\htdocs\eso\core\models\ETMemberModel.class.php on line 47

Notice: Only variables should be passed by reference in C:\xampp\htdocs\eso\core\models\ETMemberModel.class.php on line 169

Notice: Only variables should be passed by reference in C:\xampp\htdocs\eso\core\controllers\ETConversationsController.class.php on line 189

Warning: Declaration of ETActivityModel::create($type, $member, $fromMember = NULL, $data = NULL, $emailData = NULL) should be compatible with ETModel::create($values) in C:\xampp\htdocs\eso\core\models\ETActivityModel.class.php on line 101`

**version1.0.0g5
PHP version7.4.27
MySQL version10.4.22-MariaDB**

**Comment by phpSoftware** [comment]
Yes, and now you see Notice and Warning messages, this is already the case with this old script in the original version and must have nothing to do with the problem you have

Please also read this:
https://github.com/phpSoftware/esoTalk-v2/issues/1

And another hint: switch off the debug modus or the AJAX will not work correctly!

**Comment by kosmodrum12** [comment]
I uploaded the version from here without any changes and stopped all plugins and the problem remains only if debug is running.
These are just notifications and do not harm in general?

**Comment by phpSoftware** [comment]
You are right, will change the debug mode to false here.

Yes, you can ignore the notice and warnings - the script works nicely.

have a good one ;-)

**Comment by kosmodrum12** [comment]
I'm telling you, it saved my life with this update, because the owners stopped maintenance and started with Flarum, which i don't like at all...
I don't like forums based on tags.

**Comment by phpSoftware** [comment]
Nice to hear, that's the reason for me to fork it because they stopped and I also don't like Flarum ;-)

**Comment by kosmodrum12** [comment]
Is antibot for sale? because it gives me error 500 in admin.php when i set an email and password in conf.php?
I guess there is an API that checks for a license?

**Comment by phpSoftware** [comment]
All about AntiBot you will find here: https://antibot.cloud/
