### ISSUE TITLE
mysql 8 installation problem

### ISSUE THREAD

**Issue by kosmodrum12** [phpSoftware/esoTalk-v2#5]
Hello, i cant install script with mysql 8.0. I see database are uploaded in phpmyadmin but without users.

SQL Error (42000, 1064): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups, GROUP_CONCAT(g.name) AS groupNames, BIT_OR(g.canSuspend) AS canSuspe' at line 2

SELECT m.*, 
	GROUP_CONCAT(g.groupId) AS groups, 
	GROUP_CONCAT(g.name) AS groupNames, 
	BIT_OR(g.canSuspend) AS canSuspend
FROM `et_member` m
	LEFT JOIN `et_member_group` mg ON (mg.memberId=m.memberId)
	LEFT JOIN `et_group` g ON (g.groupId=mg.groupId)
WHERE (m.memberId=1)
GROUP BY m.memberId

Any ideas?

**Comment by kosmodrum12** [comment]
Already fixed.

**core/models/ETMemberModel.class.php**

`public function getWithSQL($sql)
{
	$sql->select("m.*")
		->select("GROUP_CONCAT(g.groupId) AS groups")
		->select("GROUP_CONCAT(g.name) AS groupNames")
		->select("BIT_OR(g.canSuspend) AS canSuspend")
		->from("member m")
		->from("member_group mg", "mg.memberId=m.memberId", "left")
		->from("group g", "g.groupId=mg.groupId", "left")
		->groupBy("m.memberId");`

must be;

`public function getWithSQL($sql)
{
	$sql->select("m.*")
		->select("GROUP_CONCAT(g.groupId) AS `groups`")
		->select("GROUP_CONCAT(g.name) AS `groupNames`")
		->select("BIT_OR(g.canSuspend) AS `canSuspend`")
		->from("member m")
		->from("member_group mg", "mg.memberId=m.memberId", "left")
		->from("group g", "g.groupId=mg.groupId", "left")
		->groupBy("m.memberId");`

**Comment by kosmodrum12** [comment]
Unfortunately, many things do not work with mysql 8.0 :(

**Comment by phpSoftware** [comment]
Yes, MySQL 8 and PHP 8 are very different and requires a lot of script customization.

**Comment by kosmodrum12** [comment]
I use php 7.4, but with mysql 8.0
This is one of fix for mysql 8.0 
 https://pastebin.com/w8RXBBwu

**Comment by kosmodrum12** [comment]
And one more think how can i fix css problem with long text in channels? when the text is longer, everything comes together and does not fit well
